workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG

stages:
  - build
  - lint
  - test

build:
  stage: build
  script:
    - echo '-> build!'
  rules:
    - changes:
      - build/**/*
      - .gitlab-ci.yml

lint:
  stage: lint
  script:
    - echo '-> lint!'
  rules:
    - changes:
      - lint/**/*
      - .gitlab-ci.yml

test:
  stage: test
  script:
    - echo '-> test!'
  rules:
    - when: on_success
